### ISSUE TITLE
User::addToDatabase: hit a key conflict attempting to insert a user row, but then it doesn't exist when we select it!

### ISSUE THREAD

**Issue by MikaelLindmark** [arusso/CASAuth#2]
All new users get this error when they try to login first time.

I also get this message:

Notice: Undefined variable: CASAuth in <path to my wiki>wiki/extensions/CASAuth/CASAuthSettings.php on line 103

My versions:

MediaWiki   1.21.1
PHP     5.3.3 (apache2handler)
PostgreSQL  8.4.9
CASAuth (Version 2.0.3-ucb)

**Comment by arusso** [comment]
The User::addToDatabase function is part of Mediawiki, and not specific to CASAuth, so there's nothing I can really do from the CASAuth side of things. Fortunately, someone appears to have already filed a bug report for the error you are experiencing: https://bugzilla.wikimedia.org/show_bug.cgi?id=55552

I would suggest following up with that bug report.

Regarding the undefined variable, can you show me what the line is in your `CASAuthSettings.php` file? You can use the following to extract that code along with some context (2 lines before/after):
`sed -n 101,105p CASAuthSettings.php`

**Comment by arusso** [comment]
Looks like this might be related to the PR I just accepted for #3. Can you try grabbing and installing the latest tarball, and see if that fixes the undefined variable error?

**Comment by MikaelLindmark** [comment]
Yes. it fixed the "Undefined variable" error.

**Comment by arusso** [comment]
Great, I'll go ahead and close this one out then.
